# Training configuration for PDW embedding model

# Data paths
train_pdw: "data/pdw/train_pdws.npy"  # Path to training PDW data
train_labels: "data/pdw/train_labels.npy"  # Path to training labels
ckpt: "models/transformer_encoder.pth"  # Path to save the model checkpoint

# Training parameters
batch: 32
epochs: 50
learning_rate: 0.0001
weight_decay: 0.00001
